/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppIndex: typeof import('./components/AppIndex.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IFa6BrandsXTwitter: typeof import('~icons/fa6-brands/x-twitter')['default']
    IMaterialSymbolsHiking: typeof import('~icons/material-symbols/hiking')['default']
    IMaterialSymbolsLightAwardStarOutline: typeof import('~icons/material-symbols-light/award-star-outline')['default']
    IMaterialSymbolsZoomIn: typeof import('~icons/material-symbols/zoom-in')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IMdiAward: typeof import('~icons/mdi/award')['default']
    IMdiAwardstar: typeof import('~icons/mdi/awardstar')['default']
    IMdiAwardStar: typeof import('~icons/mdi/award-star')['default']
    IMdiAwardStarOutline: typeof import('~icons/mdi/award-star-outline')['default']
    IMdiBiathlon: typeof import('~icons/mdi/biathlon')['default']
    IMdiLeaf: typeof import('~icons/mdi/leaf')['default']
    IMdiPepiconsPencilLeaf: typeof import('~icons/mdi/pepicons-pencil-leaf')['default']
    PageOne: typeof import('./components/PageOne.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
