/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/CircuitOne': RouteRecordInfo<'/CircuitOne', '/CircuitOne', Record<never, never>, Record<never, never>>,
    '/CircuitTest': RouteRecordInfo<'/CircuitTest', '/CircuitTest', Record<never, never>, Record<never, never>>,
    '/CircuitThree': RouteRecordInfo<'/CircuitThree', '/CircuitThree', Record<never, never>, Record<never, never>>,
    '/CircuitTwo': RouteRecordInfo<'/CircuitTwo', '/CircuitTwo', Record<never, never>, Record<never, never>>,
    '/Index': RouteRecordInfo<'/Index', '/Index', Record<never, never>, Record<never, never>>,
  }
}
