/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Index': RouteRecordInfo<'/Index', '/Index', Record<never, never>, Record<never, never>>,
    '/PageOne': RouteRecordInfo<'/PageOne', '/PageOne', Record<never, never>, Record<never, never>>,
    '/PageThree': RouteRecordInfo<'/PageThree', '/PageThree', Record<never, never>, Record<never, never>>,
    '/PageTwo': RouteRecordInfo<'/PageTwo', '/PageTwo', Record<never, never>, Record<never, never>>,
    '/Test': RouteRecordInfo<'/Test', '/Test', Record<never, never>, Record<never, never>>,
  }
}
